apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
  - image: ocarnal/hello
    name: hello-container
    ports:
    - containerPort: 8085
      protocol: TCP

